<?php

function crassignments_menu() {
  $items = array();
  $items['add_assignment'] = array(
    'title' => 'Add assignment',
    'description' => 'Add assignments',
    'page callback' => 'add_assign',
    'access arguments' => array('access_crassignments_settings'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'user-menu',
  );

  $items['submitted'] = array(
    'title' => 'Submitted assignments',
    'description' => 'View submitted assignments',
    'page callback' => 'submitted_page',
    'access arguments' => array('access_crassignments_settings'),
     'type' => MENU_NORMAL_ITEM,
     'menu_name' => 'user-menu',
  );

  $items['given'] = array(
    'title' => 'My assignments',
    'description' => 'View given assignments',
    'page callback' => 'given_page',
    'access arguments' => array('access_crassignments_settings'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
  );
  return $items;
}

/*function to redirect user to add assignment page*/

function add_assign() {
  global $user;
  $user->name;
  $user_name = variable_get($user->name);
  if ($user_name == 1) {
    drupal_goto("node/add/cplus");
  }
  elseif ($user_name == 2) {
    drupal_goto("node/add/dotnet");
  }
  elseif ($user_name == 3) {
    drupal_goto("node/add/drupal");
  }
  else {
    drupal_deliver_page(MENU_ACCESS_DENIED);
  }
}

/*function to redirect user to submitted assignments page*/

function submitted_page() {
  global $user;
  $user->name;
  $user_name = variable_get($user->name);
  if ($user_name == 1) {
    drupal_goto("c-assignments");
  }
  elseif ($user_name == 2) {
    drupal_goto("dotnet-assignments");
  }
  elseif ($user_name == 3) {
    drupal_goto("drupal");
  }
  else {
    drupal_deliver_page(MENU_ACCESS_DENIED);
  }
}

/*function to  redirect user to my assignments page*/

function given_page() {
  global $user;
  $user->name;
  $user_name = variable_get($user->name);
  if ($user_name == 1) {
    drupal_goto("c-given-assignments");
  }
  elseif ($user_name == 2) {
    drupal_goto("dotnet-given-assignments");
  }
  elseif ($user_name == 3) {
    drupal_goto("drupal-given-assignments");
  }
  else {
   drupal_deliver_page(MENU_ACCESS_DENIED);
  }
}

/*function view assignment of particular title*/

function crassignments_node_view($node, $view_mode) {

  variable_set('assignName' , $node->title);
  variable_set('assignType' , $node->type);
  global $user;
  if (isset($user->name)) {
    $user->name;
    $user_name = variable_get($user->name);
    if (isset($user->roles[5])) {
      if ($node->type!='advanced_assignments' && $node->type!='beginner_assignment' && $node->type!='senior_assignment' ) {
        if ($user_name == 1) {
          $alias = str_replace(" " , "+" , $node->title );
          $node->content['submit_assign'] = array(
            "#markup" => '<a href=http://localhost/c-assignments?created=&title=' . $alias . '>Click to view sbmitted assignments</a>',
            "#weight" => 100
          );
      }
      elseif ($user_name == 2) {
        $alias = str_replace(" " , "+" , $node->title );
        $node->content['submit_assign'] = array(
          "#markup" => '<a href=http://localhost/dotnet-assignments?created=&title=' . $alias . '>Click to view sbmitted assignments</a>',
          "#weight" => 100
        );
        }
        elseif ($user_name == 3) {
          $alias = str_replace(" " , "+" , $node->title );
          $node->content['submit_assign'] = array(
            "#markup" => '<a href=http://localhost/drupal?created=&title=' . $alias . '>Click to view sbmitted assignments</a>',
                 "#weight" => 100
          );
        }
        else{
          drupal_deliver_page(MENU_ACCESS_DENIED);
        }
        return $node;
      }
    }
  }
}

/*permissions for the module*/

function crassignments_permission() {
  $items = array();
  $items['access_crassignments_settings'] = array(
    'title' => 'Allow access to assignments',
    'description' => 'Setting to assignments',
  );
  return $items;
}
